# Generated by Django 2.0.1 on 2019-06-06 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='contratada',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contratada'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='convenio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Convênio'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Fase'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='prazo_dias',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
